server:
  port: 19091

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
      discovery:
        locator:
          enabled: true


jwt:
  secret-key: aGVsbG9qd3RzcHJpbmdoZWxsb2p3dHNwcmluZ2hlbGxvand0c3ByaW5naGVsbG9qd3RzcHJpbmdoZWxsb2p3dHNwcmluZ2hlbGxvand0c3ByaW5n

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/