server:
  port: 19093

  #spring.datasource.url=jdbc:h2:mem:test
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/java-workspace/my-project/database-files/my-own-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/